package r2i.free.r2k.pointblqdao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import r2i.free.r2k.pointblqdao.db.Info;
import r2i.free.r2k.pointblqdao.db.Type_Point;
import r2i.free.r2k.pointblqdao.db.Moyens;
import r2i.free.r2k.pointblqdao.db.Solution;

import r2i.free.r2k.pointblqdao.db.InfoDao;
import r2i.free.r2k.pointblqdao.db.Type_PointDao;
import r2i.free.r2k.pointblqdao.db.MoyensDao;
import r2i.free.r2k.pointblqdao.db.SolutionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig infoDaoConfig;
    private final DaoConfig type_PointDaoConfig;
    private final DaoConfig moyensDaoConfig;
    private final DaoConfig solutionDaoConfig;

    private final InfoDao infoDao;
    private final Type_PointDao type_PointDao;
    private final MoyensDao moyensDao;
    private final SolutionDao solutionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        infoDaoConfig = daoConfigMap.get(InfoDao.class).clone();
        infoDaoConfig.initIdentityScope(type);

        type_PointDaoConfig = daoConfigMap.get(Type_PointDao.class).clone();
        type_PointDaoConfig.initIdentityScope(type);

        moyensDaoConfig = daoConfigMap.get(MoyensDao.class).clone();
        moyensDaoConfig.initIdentityScope(type);

        solutionDaoConfig = daoConfigMap.get(SolutionDao.class).clone();
        solutionDaoConfig.initIdentityScope(type);

        infoDao = new InfoDao(infoDaoConfig, this);
        type_PointDao = new Type_PointDao(type_PointDaoConfig, this);
        moyensDao = new MoyensDao(moyensDaoConfig, this);
        solutionDao = new SolutionDao(solutionDaoConfig, this);

        registerDao(Info.class, infoDao);
        registerDao(Type_Point.class, type_PointDao);
        registerDao(Moyens.class, moyensDao);
        registerDao(Solution.class, solutionDao);
    }
    
    public void clear() {
        infoDaoConfig.getIdentityScope().clear();
        type_PointDaoConfig.getIdentityScope().clear();
        moyensDaoConfig.getIdentityScope().clear();
        solutionDaoConfig.getIdentityScope().clear();
    }

    public InfoDao getInfoDao() {
        return infoDao;
    }

    public Type_PointDao getType_PointDao() {
        return type_PointDao;
    }

    public MoyensDao getMoyensDao() {
        return moyensDao;
    }

    public SolutionDao getSolutionDao() {
        return solutionDao;
    }

}
