package r2i.free.r2k.pointblqdao.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "INFO".
 */
public class Info {

    private Long id;
    private java.util.Date date_controle;
    /** Not-null value. */
    private String user;
    private String entreprise;
    private String respo;
    private String adr;
    private String ref;
    private Integer nature_trvx;
    private Integer enviro;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Info() {
    }

    public Info(Long id) {
        this.id = id;
    }

    public Info(Long id, java.util.Date date_controle, String user, String entreprise, String respo, String adr, String ref, Integer nature_trvx, Integer enviro) {
        this.id = id;
        this.date_controle = date_controle;
        this.user = user;
        this.entreprise = entreprise;
        this.respo = respo;
        this.adr = adr;
        this.ref = ref;
        this.nature_trvx = nature_trvx;
        this.enviro = enviro;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate_controle() {
        return date_controle;
    }

    public void setDate_controle(java.util.Date date_controle) {
        this.date_controle = date_controle;
    }

    /** Not-null value. */
    public String getUser() {
        return user;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser(String user) {
        this.user = user;
    }

    public String getEntreprise() {
        return entreprise;
    }

    public void setEntreprise(String entreprise) {
        this.entreprise = entreprise;
    }

    public String getRespo() {
        return respo;
    }

    public void setRespo(String respo) {
        this.respo = respo;
    }

    public String getAdr() {
        return adr;
    }

    public void setAdr(String adr) {
        this.adr = adr;
    }

    public String getRef() {
        return ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public Integer getNature_trvx() {
        return nature_trvx;
    }

    public void setNature_trvx(Integer nature_trvx) {
        this.nature_trvx = nature_trvx;
    }

    public Integer getEnviro() {
        return enviro;
    }

    public void setEnviro(Integer enviro) {
        this.enviro = enviro;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
