package r2i.free.r2k.pointblqdao.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MOYENS".
 */
public class Moyens {

    private Long id;
    private Integer aigui_comp;
    private Integer aigui_aiuill;
    private Integer aigui_canne;
    private Integer hydro;
    private Integer id_pointblq;
    private Integer id_sonde;
    private Integer tenta_contact;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Moyens() {
    }

    public Moyens(Long id) {
        this.id = id;
    }

    public Moyens(Long id, Integer aigui_comp, Integer aigui_aiuill, Integer aigui_canne, Integer hydro, Integer id_pointblq, Integer id_sonde, Integer tenta_contact) {
        this.id = id;
        this.aigui_comp = aigui_comp;
        this.aigui_aiuill = aigui_aiuill;
        this.aigui_canne = aigui_canne;
        this.hydro = hydro;
        this.id_pointblq = id_pointblq;
        this.id_sonde = id_sonde;
        this.tenta_contact = tenta_contact;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAigui_comp() {
        return aigui_comp;
    }

    public void setAigui_comp(Integer aigui_comp) {
        this.aigui_comp = aigui_comp;
    }

    public Integer getAigui_aiuill() {
        return aigui_aiuill;
    }

    public void setAigui_aiuill(Integer aigui_aiuill) {
        this.aigui_aiuill = aigui_aiuill;
    }

    public Integer getAigui_canne() {
        return aigui_canne;
    }

    public void setAigui_canne(Integer aigui_canne) {
        this.aigui_canne = aigui_canne;
    }

    public Integer getHydro() {
        return hydro;
    }

    public void setHydro(Integer hydro) {
        this.hydro = hydro;
    }

    public Integer getId_pointblq() {
        return id_pointblq;
    }

    public void setId_pointblq(Integer id_pointblq) {
        this.id_pointblq = id_pointblq;
    }

    public Integer getId_sonde() {
        return id_sonde;
    }

    public void setId_sonde(Integer id_sonde) {
        this.id_sonde = id_sonde;
    }

    public Integer getTenta_contact() {
        return tenta_contact;
    }

    public void setTenta_contact(Integer tenta_contact) {
        this.tenta_contact = tenta_contact;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
