package r2i.free.r2k.pointblqdao.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SOLUTION".
 */
public class Solution {

    private Long id;
    private Integer aigui_compr;
    private Integer aigui_aigui;
    private Integer aigui_cann;
    private Integer hydro;
    private Integer change_parc;
    private Integer fouill_ponct;
    private Integer genie_civi;
    private Integer nego;
    private Integer accomp_free;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Solution() {
    }

    public Solution(Long id) {
        this.id = id;
    }

    public Solution(Long id, Integer aigui_compr, Integer aigui_aigui, Integer aigui_cann, Integer hydro, Integer change_parc, Integer fouill_ponct, Integer genie_civi, Integer nego, Integer accomp_free) {
        this.id = id;
        this.aigui_compr = aigui_compr;
        this.aigui_aigui = aigui_aigui;
        this.aigui_cann = aigui_cann;
        this.hydro = hydro;
        this.change_parc = change_parc;
        this.fouill_ponct = fouill_ponct;
        this.genie_civi = genie_civi;
        this.nego = nego;
        this.accomp_free = accomp_free;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAigui_compr() {
        return aigui_compr;
    }

    public void setAigui_compr(Integer aigui_compr) {
        this.aigui_compr = aigui_compr;
    }

    public Integer getAigui_aigui() {
        return aigui_aigui;
    }

    public void setAigui_aigui(Integer aigui_aigui) {
        this.aigui_aigui = aigui_aigui;
    }

    public Integer getAigui_cann() {
        return aigui_cann;
    }

    public void setAigui_cann(Integer aigui_cann) {
        this.aigui_cann = aigui_cann;
    }

    public Integer getHydro() {
        return hydro;
    }

    public void setHydro(Integer hydro) {
        this.hydro = hydro;
    }

    public Integer getChange_parc() {
        return change_parc;
    }

    public void setChange_parc(Integer change_parc) {
        this.change_parc = change_parc;
    }

    public Integer getFouill_ponct() {
        return fouill_ponct;
    }

    public void setFouill_ponct(Integer fouill_ponct) {
        this.fouill_ponct = fouill_ponct;
    }

    public Integer getGenie_civi() {
        return genie_civi;
    }

    public void setGenie_civi(Integer genie_civi) {
        this.genie_civi = genie_civi;
    }

    public Integer getNego() {
        return nego;
    }

    public void setNego(Integer nego) {
        this.nego = nego;
    }

    public Integer getAccomp_free() {
        return accomp_free;
    }

    public void setAccomp_free(Integer accomp_free) {
        this.accomp_free = accomp_free;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
