package r2i.free.r2k.pointblqdao.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TYPE__POINT".
 */
public class Type_Point {

    private Long id;
    private Integer res_aer;
    private Integer conduit_sat;
    private Integer conduit_cass;
    private Integer tamp_chamb;
    private Integer chamb_enrob;
    private Integer res_priv;
    private Integer chamb_inex;
    private Integer problem_acce;
    private String autre;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Type_Point() {
    }

    public Type_Point(Long id) {
        this.id = id;
    }

    public Type_Point(Long id, Integer res_aer, Integer conduit_sat, Integer conduit_cass, Integer tamp_chamb, Integer chamb_enrob, Integer res_priv, Integer chamb_inex, Integer problem_acce, String autre) {
        this.id = id;
        this.res_aer = res_aer;
        this.conduit_sat = conduit_sat;
        this.conduit_cass = conduit_cass;
        this.tamp_chamb = tamp_chamb;
        this.chamb_enrob = chamb_enrob;
        this.res_priv = res_priv;
        this.chamb_inex = chamb_inex;
        this.problem_acce = problem_acce;
        this.autre = autre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRes_aer() {
        return res_aer;
    }

    public void setRes_aer(Integer res_aer) {
        this.res_aer = res_aer;
    }

    public Integer getConduit_sat() {
        return conduit_sat;
    }

    public void setConduit_sat(Integer conduit_sat) {
        this.conduit_sat = conduit_sat;
    }

    public Integer getConduit_cass() {
        return conduit_cass;
    }

    public void setConduit_cass(Integer conduit_cass) {
        this.conduit_cass = conduit_cass;
    }

    public Integer getTamp_chamb() {
        return tamp_chamb;
    }

    public void setTamp_chamb(Integer tamp_chamb) {
        this.tamp_chamb = tamp_chamb;
    }

    public Integer getChamb_enrob() {
        return chamb_enrob;
    }

    public void setChamb_enrob(Integer chamb_enrob) {
        this.chamb_enrob = chamb_enrob;
    }

    public Integer getRes_priv() {
        return res_priv;
    }

    public void setRes_priv(Integer res_priv) {
        this.res_priv = res_priv;
    }

    public Integer getChamb_inex() {
        return chamb_inex;
    }

    public void setChamb_inex(Integer chamb_inex) {
        this.chamb_inex = chamb_inex;
    }

    public Integer getProblem_acce() {
        return problem_acce;
    }

    public void setProblem_acce(Integer problem_acce) {
        this.problem_acce = problem_acce;
    }

    public String getAutre() {
        return autre;
    }

    public void setAutre(String autre) {
        this.autre = autre;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
